name: CI/CD - FastAPI Docker App with GHCR and Azuree

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: fastapi-app
  IMAGE_TAG: v1
  GHCR_REPO: ghcr.io/umapoornima/fastapi-app  # Make sure this is all lowercase

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u umapoornima --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t $GHCR_REPO:$IMAGE_TAG .
          docker push $GHCR_REPO:$IMAGE_TAG

      - name: Azure Login via credentials JSON
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker image to Azure App Service
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name $GHCR_REPO:$IMAGE_TAG \
            --docker-registry-server-url https://ghcr.io \
            --docker-registry-server-user umapoornima \
            --docker-registry-server-password ${{ secrets.GHCR_TOKEN }}

      - name: Restart Azure App Service (optional but recommended)
        run: |
          az webapp restart \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
