name: CI/CD - FastAPI to Azure using GHCR

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and Push Docker Image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:v1
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Azure Login via SP
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure App Service to use GHCR image
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --container-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app:v1 \
          --container-registry-server-url https://ghcr.io \
          --container-registry-user ${{ secrets.GHCR_USERNAME }} \
          --container-registry-password ${{ secrets.GHCR_TOKEN }}
