name: CI/CD - FastAPI to Azure using GHCR

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: fastapi-app
  IMAGE_TAG: v1
  GHCR_REPO: ghcr.io/${{ secrets.GHCR_USERNAME }}/fastapi-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and Push Docker Image to GHCR
      run: |
        docker build -t $GHCR_REPO:$IMAGE_TAG .
        docker push $GHCR_REPO:$IMAGE_TAG

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --container-image-name $GHCR_REPO:$IMAGE_TAG \
          --docker-registry-server-url https://ghcr.io \
          --docker-registry-server-user ${{ secrets.GHCR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.GHCR_TOKEN }}
