name: Build and Deploy FastAPI using Docker and Service Principal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Azure using Service Principal
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push Docker image to ACR
      run: |
        IMAGE_NAME=fastapi-app
        IMAGE_TAG=v3
        ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY }}

        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG

    - name: Deploy to Azure App Service (Linux Container)
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --container-image-name ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/fastapi-app:v3 \
          --enable-app-service-storage false
